version: '3.8'

services:
  server:
    build: .
    restart: on-failure
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json
      - ./ui:/ui

  worker:
    build: .
    restart: on-failure
    entrypoint: [ "./blnk", "workers"]
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  migration:
    build: .
    entrypoint: [ "./blnk", "migrate","up" ]
    depends_on:
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blnk
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
      - ./promtail/config.yaml:/etc/promtail/config.y-ml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

volumes:
  pg_data:

networks:
  loki:
