name: "blnk"

services:
  server:
    image: jerryenebeli/blnk:v0.5.0
    restart: on-failure
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - postgres
      - migration
    volumes:
      - ./blnk.json:/blnk.json
      - ./ui:/ui
    environment:
      - OUTBOUND_HOST_PORT=service-b:8082
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true

  worker:
    image: jerryenebeli/blnk:v0.5.0
    restart: on-failure
    entrypoint: ["./blnk", "workers"]
    depends_on:
      - redis
      - postgres
      - migration
    volumes:
      - ./blnk.json:/blnk.json
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  migration:
    image: jerryenebeli/blnk:v0.5.0
    entrypoint: ["./blnk", "migrate", "up"]
    depends_on:
      - postgres
    volumes:
      - ./blnk.json:/blnk.json
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"

  redis:
    image: redis:7.2.4

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blnk
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
